name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    schedule:
      - cron: '20 9 4 * *' # Monthly builds

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: iank1/catflow_service_videosplit
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=schedule,pattern=nightly

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install .[dev]

    - name: Test with pytest
      run: |
        pytest

    - name: Docker Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
